lobby-server: lobby
mysql:
  enable: false
  host: "localhost"
  port: "3306"
  database: "drawit"
  username: "root"
  password: ""


#For 1.8 you can use Material:Data
lobby-items:
  game-selector:
    material: CHEST
    slot: 0
    enchanted: false
    command: di gui
  back-to-hub:
    material: ARROW
    slot: 8
    enchanted: false
    command: di leave

drawer-tools:
  thin-brush:
    material: WOOD_SWORD
    enchanted: false
    slot: 0
  thick-brush:
    material: DIAMOND_SWORD
    enchanted: false
    slot: 1
  spray-canvas:
    material: SHEARS
    enchanted: false
    slot: 2
  fill-can:
    material: BUCKET
    enchanted: false
    slot: 3
  burn-canvas:
    material: BLAZE_POWDER
    enchanted: false
    slot: 8

color-picker:
  - "0; &7Orange; WOOL; 1"
  - "1; &7Magenta; WOOL; 2"
  - "2; &7Light Blue; WOOL; 3"
  - "3; &7Yellow; WOOL; 4"
  - "4; &7Lime; WOOL; 5"
  - "5; &7Cyan; WOOL; 9"
  - "6; &7Purple; WOOL; 10"
  - "7; &7Blue; WOOL; 11"
  - "8; &7Green; WOOL; 13"
  - "9; &7Red; WOOL; 14"
  - "10; &7Pastel Orange; STAINED_CLAY; 1"
  - "11; &7Pastel Magenta; STAINED_CLAY; 2"
  - "12; &7Pastel Light Blue; STAINED_CLAY; 3"
  - "13; &7Pastel Yellow; STAINED_CLAY; 4"
  - "14; &7Pastel Lime; STAINED_CLAY; 5"
  - "15; &7Pastel Cyan; STAINED_CLAY; 9"
  - "16; &7Pastel Purple; STAINED_CLAY; 10"
  - "17; &7Pastel Blue; STAINED_CLAY; 11"
  - "18; &7Pastel Green; STAINED_CLAY; 13"
  - "19; &7Pastel Red; STAINED_CLAY; 14"
  - "20; &7Gold; GOLD_BLOCK; 0"
  - "21; &7Diamond; DIAMOND_BLOCK; 0"
  - "22; &7Redstone; REDSTONE_BLOCK; 0"
  - "23; &7Sponge; SPONGE; 0"
  - "27; &7Pink; WOOL; 6"
  - "29; &7Emerald; EMERALD_BLOCK; 0"
  - "31; &7Black; WOOL; 15"
  - "32; &7Brown; WOOL; 12"
  - "33; &7Gray; WOOL; 7"
  - "34; &7Light Gray; WOOL; 8"
  - "35; &7White; WOOL; 0"
  - "36; &7Pastel Pink; STAINED_CLAY; 6"
  - "38; &7Iron; IRON_BLOCK; 0"
  - "40; &7Pastel Black; STAINED_CLAY; 15"
  - "41; &7Pastel Brown; STAINED_CLAY; 12"
  - "42; &7Pastel Gray; STAINED_CLAY; 7"
  - "43; &7Pastel Light Gray; STAINED_CLAY; 8"
  - "44; &7Pastel White; STAINED_CLAY; 0"


stats:
  tokens:
    per-right-guess: 2
    victory: 40
  drawer-points:
    per-right-word: 2
  guesser-points:
    1: 10
    2: 8
    3: 6
    4: 4
    other: 2