main: me.MrIronMan.drawit.DrawIt
name: DrawIt
author: MrIronMan
version: 1.0
api-version: "1.13"
description: DrawIt Mini-game by MrIronMan (MherZaqaryan)
softdepend: [PlaceholderAPI]

permissions:
  DrawIt.*:
    description: Allow to use all DrawIt commands
    children:
      DrawIt.Setup: true
      DrawIt.Delete: true
      DrawIt.ForceStart: true
      DrawIt.AddPoints: true
      DrawIt.Reload: true
      DrawIt.Main: true
      DrawIt.BuildMode: true
      DrawIt.Skip: true