main: club.mher.drawit.DrawIt
name: DrawIt
author: Mher Zaqaryan
version: ${project.version}
api-version: "1.13"
description: DrawIt Mini-game by Mher Zaqaryan
softdepend: [PlaceholderAPI]

permissions:
  DrawIt.*:
    description: Allow to use all commands
  DrawIt.Setup:
    description: Allow to setup game.
  DrawIt.Delete:
    description: Allow to delete game.
  DrawIt.ForceStart:
    description: Allow to force start game.
  DrawIt.AddPoints:
    description: Allow to add player points.
  DrawIt.Reload:
    description: Allow to reload configuration files.
  DrawIt.Main:
    description: Allow to see all list of commands.
  DrawIt.BuildMode:
    description: Allow to enable/disable build mode.
  DrawIt.Skip:
    description: Allow to skip the word in game.